frontend:
  replicaCount: 1
  image:
    tag: "01e9efcf20b814fc92af93a97b3084e28a992d0e"
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 20m
      memory: 32Mi

backend:
  replicaCount: 1
  image:
    tag: "01e9efcf20b814fc92af93a97b3084e28a992d0e"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

database:
  replicaCount: 1
  postgresql:
    storage: "1Gi"
